# This is a basic workflow to help you get started with Actions

name: Tests & Lint

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pylint-exit
    - name: Run pylint 
      run: |
        pylint --fail-under=7.0 $(find . -type f -name "*.py" -not -path './build*' -not -path './.vscode/*'| xargs) \
          | tee pylint.txt 
    - name: Upload pylint.txt
      uses: actions/upload-artifact@v2
      with:
        name: pylint report
        path: pylint.txt

  testcoverage:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.4
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Set up Python 3.8
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov

      # Runs a set of commands using the runners shell
      - name: Run Tests
        run: pytest --cov-report xml --cov-report html --cov=lazyConfig tests/

      - name: Upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
      
      - name: Upload HTML results
        uses: actions/upload-artifact@v2
        with:
          name: Test Coverage Report
          path: htmlcov
      
